# إعدادات الموقع العامة
title: "أخبار الجزائر اليوم"
description: "آخر المستجدات والأحداث في الجزائر."
lang: "ar"
timezone: "Africa/Algiers"

# إعدادات الاستضافة (ضرورية جداً لعمل الموقع)
baseurl: "/algeria_news" 
url: "https://[sasu556].github.io" # استبدل [username] باسم مستخدم GitHub الخاص بك

# اختيار القالب (هذا يمنع ظهور الأكواد البرمجية كنص عادي)
theme: minima

# إعدادات إضافية اختيارية
encoding: "UTF-8"
